#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""Modify nullables and defaults."""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1777230124"
down_revision = "1754318294"
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "vcs_releases",
        "provider_id",
        existing_type=sa.VARCHAR(length=255),
        nullable=True,
    )
    op.alter_column(
        "vcs_releases",
        "provider",
        existing_type=sa.VARCHAR(length=255),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "vcs_releases", "tag", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "vcs_releases", "repository_id", existing_type=sa.UUID(), nullable=True
    )
    op.alter_column(
        "vcs_releases",
        "record_is_draft",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "vcs_releases", "status", existing_type=sa.CHAR(length=1), nullable=False
    )
    op.alter_column(
        "vcs_repositories",
        "provider",
        existing_type=sa.VARCHAR(length=255),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "vcs_repositories",
        "default_branch",
        existing_type=sa.VARCHAR(length=255),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "vcs_repositories",
        "default_branch",
        existing_type=sa.VARCHAR(length=255),
        server_default=sa.text("'main'::character varying"),
        existing_nullable=False,
    )
    op.alter_column(
        "vcs_repositories",
        "provider",
        existing_type=sa.VARCHAR(length=255),
        server_default=sa.text("'github'::character varying"),
        existing_nullable=False,
    )
    op.alter_column(
        "vcs_releases", "status", existing_type=sa.CHAR(length=1), nullable=True
    )
    op.alter_column(
        "vcs_releases",
        "record_is_draft",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=True,
    )
    op.alter_column(
        "vcs_releases", "repository_id", existing_type=sa.UUID(), nullable=False
    )
    op.alter_column(
        "vcs_releases", "tag", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "vcs_releases",
        "provider",
        existing_type=sa.VARCHAR(length=255),
        server_default=sa.text("'github'::character varying"),
        existing_nullable=False,
    )
    op.alter_column(
        "vcs_releases",
        "provider_id",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
    )
    # ### end Alembic commands ###
